### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by iamkieranbolger** [MAKIO135/MultiLayeredVideoSequencer#11]
This software looks amazing and I want to try it, but I need to know how to compile/install it. I've looked at all the files here and don't see any installation instructions.

**Comment by MAKIO135** [comment]
This is the sources for a Processing sketch. Thus you need to download Processing 1.5.1 ( http://processing.org/download/ ) and install libraries listed on the readme:
GSVideo 1.0.0: http://sourceforge.net/projects/gsvideo/files/gsvideo/1.0/
GLGraphics 1.0.0: http://sourceforge.net/projects/glgraphics/files/glgraphics/1.0/
ControlP5 1.5.2: http://code.google.com/p/controlp5/downloads/list
JSON4Processing 1.3.1: https://github.com/MAKIO135/JSON-processing

And then open "MultiLayeredVideoSequencer.pde" with Processingto load sources and run it.

**Comment by iamkieranbolger** [comment]
Thanks! I've never used processing before, this helps massively!
